version: "3.9"

services:
  tater:
    build: .
    container_name: tater_app
    ports:
      - "8501:8501"  # Streamlit web UI
    environment:
      LLM_HOST: ${LLM_HOST}
      LLM_PORT: ${LLM_PORT}
      LLM_MODEL: ${LLM_MODEL}
      LLM_EMB_MODEL: ${LLM_EMB_MODEL}
      CONTEXT_LENGTH: ${CONTEXT_LENGTH}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTOMATIC_URL: ${AUTOMATIC_URL}
      PREMIUMIZE_API_KEY: ${PREMIUMIZE_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: tater_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
