version: "3.9"

services:
  tater:
    build: .
    container_name: tater_app
    ports:
      - "8501:8501"  # Streamlit web UI
    environment:
      OLLAMA_HOST: ${OLLAMA_HOST}
      OLLAMA_PORT: ${OLLAMA_PORT}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_EMB_MODEL: ${OLLAMA_EMB_MODEL}
      CONTEXT_LENGTH: ${CONTEXT_LENGTH}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: tater_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
